name: Hello world
on: workflow_dispatch
jobs:
 Buid:
  runs-on: ubuntu-latest
  steps:
     - name: build step
       run: echo " A run buid step"


 Deploy:
  runs-on: ubuntu-latest
  steps:
    - name: deploy step
      run: echo " Deploy the code"

  Test:
   runs-on: ubuntu-latest
   steps:
     - name: test phase
       run: eho " testing the code"
   

